In [1]:
# this is a code cell, and, specifically, this is a Python comment
print("Hello World")

Hello World


In [2]:
a='text'
a?

In [3]:
l = [1,2,3,4,5] #this is a list (square brackets)
t = (1,2,3,4,5) #this is a tuple (round brackets)
print(l)
print(t)

[1, 2, 3, 4, 5]
(1, 2, 3, 4, 5)


In [4]:
print(l[0],l[2])
print(t[0],t[3])
l[0]=8
print(l)

1 3
1 4
[8, 2, 3, 4, 5]


In [5]:
try:
    t[2]=5 #this will yield an error since tuples are immutable
except:
    print("This will raise an exception!")

This will raise an exception!


In [6]:
t=(1)
t?

In [7]:
t=(1,)
t?

In [8]:
l=[1,2,3,4,5,6,7,8]
t=(4,5,6,7,4,8,2,4)
ttl = list(t)
ltt = tuple(l)

print(ttl)
print(ltt)

[4, 5, 6, 7, 4, 8, 2, 4]
(1, 2, 3, 4, 5, 6, 7, 8)


In [9]:
print ("t[0:3]      ->", t[0:3]) #from index 0 (included) to index 3 (excluded)
print ("l[1:3]      ->", l[1:2]) #from index 1 (included) to index 2 (excluded)
print ("t[0:]       ->", t[1:]) #from index 1 (included) to the last index (second index is omitted)
print ("l[:2]       ->", l[:2]) #from index 0 (omitted) to index 2 (excluded)
print ("t[0:7:1]    ->", t[0:8:1]) #from index 0 (included) to index 8 (excluded) at a step of 1 (i.e., all numbers)
print ("l[0:7:2]    ->", l[0:8:2]) #from index 0 (included) to index 8 (excluded) at a step of 2 (i.e., every other number)
print ("t[::2]      ->", t[::2]) #from index 0 (omitted) to index 8 (omitted) at a step of 2 (equivalent to the previous one)
print ("l[-1]       ->", l[-1]) #last number
print ("t[-2]       ->", t[-2]) #second-last numebr
print ("l[-5]       ->", l[-5]) #fifth-last numebr
print ("t[-3:]      ->", t[-3:]) #last three number
print ("l[:-3]      ->", l[:-3]) #from index 0 (omitted) to third-last index (excluded)
print ("t[-1:-5:-1] ->", t[-1:-5:-1]) #from the penultimate index to the fifth-last index (excluded) at a step of -1
print ("l[-1:0:-1]  ->", l[-1:0:-1]) #from the penultimate index to index 0 (excluded) at a step of -1
print ("l[::-1]     ->", l[::-1]) #reverse the list

t[0:3]      -> (4, 5, 6)
l[1:3]      -> [2]
t[0:]       -> (5, 6, 7, 4, 8, 2, 4)
l[:2]       -> [1, 2]
t[0:7:1]    -> (4, 5, 6, 7, 4, 8, 2, 4)
l[0:7:2]    -> [1, 3, 5, 7]
t[::2]      -> (4, 6, 4, 2)
l[-1]       -> 8
t[-2]       -> 2
l[-5]       -> 4
t[-3:]      -> (8, 2, 4)
l[:-3]      -> [1, 2, 3, 4, 5]
t[-1:-5:-1] -> (4, 2, 8, 4)
l[-1:0:-1]  -> [8, 7, 6, 5, 4, 3, 2]
l[::-1]     -> [8, 7, 6, 5, 4, 3, 2, 1]


In [10]:
true_condition = True
false_condition = False

if true_condition: #always remeber about the colon
    print ("cool!") #indentation here is mandatory
    
if false_condition: #false condition should not fire
    print ("not cool :(")
    
if not false_condition: #negate boolean value using "not"
    print ("cool again :)")
    
if false_condition:
    print ("false")
else: #note indentation and colon here
    print ("true")
    
if false_condition:
    print ("false")
elif 5>4: #"else if" is abbreviated as "elif"
    print ("5>4")
else:
    print ("4<5??")

cool!
cool again :)
true
5>4


In [11]:
l=[1,6,2,5,7]

if 5 in l:
    print ("5 in l")
    
if 8 in l:
    print ("8 in l")

5 in l


In [12]:
i=0
while i<5: #colon
    print (i) #indentation
    i+=1

0
1
2
3
4


In [13]:
l=[1,7,2,5]
for v in l:
    print (v)

1
7
2
5


In [14]:
for i in range(5):
    print (i)

0
1
2
3
4


In [15]:
array=[1,7,2,4,5] 
for i in range(len(array)): #standard notation
    print (i,"->",array[i])

0 -> 1
1 -> 7
2 -> 2
3 -> 4
4 -> 5


In [16]:
for index,value in enumerate(array): #get both index and value
    print (index,"->",value)

0 -> 1
1 -> 7
2 -> 2
3 -> 4
4 -> 5


In [17]:
a1=[1,6,2,5]
a2=[1,8,2,7]

for v1,v2 in zip(a1,a2): #iterate twi arrays at once!
    print (v1,v2)

1 1
6 8
2 2
5 7


In [18]:
import numpy as np #now we can reference numpy simply by "np"

In [19]:
l = [[1,2,3],[4,5,2],[1,8,3]] #this is a list of lists
print ("List of lists:",l)
a = np.array(l) #this is a numpy array
print ("Numpy array:\n",a)
print ("Numpy array from tuple:",np.array((1,2,3)))

List of lists: [[1, 2, 3], [4, 5, 2], [1, 8, 3]]
Numpy array:
 [[1 2 3]
 [4 5 2]
 [1 8 3]]
Numpy array from tuple: [1 2 3]


In [20]:
a1 = np.array([1,2,3,4]) #this is a numpy array
a2 = np.array([5,2,1,4]) #another numpy array
m1 = np.array([[1,2,3,4],[5,4,2,3],[7,5,3,2],[0,2,3,1]]) #this is a numpy 4x4 matrix
m2 = np.array([[8,2,3,1],[1,5,3,6],[1,2,7,5],[4,5,2,1]]) #another numpy 4x4 matrix
print ('Array:',a1)
print ('Array:',a2)
print ('Matrix:\n',m1)
print ('matrix:\n',m2)

Array: [1 2 3 4]
Array: [5 2 1 4]
Matrix:
 [[1 2 3 4]
 [5 4 2 3]
 [7 5 3 2]
 [0 2 3 1]]
matrix:
 [[8 2 3 1]
 [1 5 3 6]
 [1 2 7 5]
 [4 5 2 1]]


In [21]:
print ("Shape:",a1.shape) #print the array shape
print ("Shape:",a2.shape) #vectors are monodimensional array of 4 elements
print ("Sum:",a1+a2) #vector sum
print ("Elementwise multiplication:",a1*a2) #elementwise multiplication
print ("Power of two:",a1**2) #power of two
print ("Elementwise power:",a1**a2) #elementwise power operation
print ("Vector product:",a1.dot(a2)) #vector product
print ("Minimum:",a1.min()) #array minumum
print ("Maximum:",a1.max()) #array maximum
print ("Sum:",a2.sum()) #sum of all values
print ("Mean:",a1.mean()) #array mean

Shape: (4,)
Shape: (4,)
Sum: [6 4 4 8]
Elementwise multiplication: [ 5  4  3 16]
Power of two: [ 1  4  9 16]
Elementwise power: [  1   4   3 256]
Vector product: 28
Minimum: 1
Maximum: 4
Sum: 12
Mean: 2.5


In [22]:
print ("Shape:",m1.shape) #matrix shape
print ("Shape:",m2.shape) #matrices are 4x4
print ("Sum:",m1+m2) #sum
print ("Elementwise product:",m1*m2) #elementwise product
print ("Power of two:",m1**2) #power of two
print ("Elementwise power:",m1**m2) #elementwise power
print ("Matrix multiplication:",m1.dot(m2)) #matrix multiplication
print ("Minimum:",m1.min()) #minumum
print ("Maximum:",m1.max()) #maximum
print ("Minimum along columns:",m1.min(0)) #minumum along columns
print ("Minimum along rows:",m1.min(1)) #minimum along rows
print ("Sum:",m1.sum()) #mean value
print ("Mean:",m1.mean()) #mean value
print ("Diagonal:",m1.diagonal()) #diagonal of the matrix

Shape: (4, 4)
Shape: (4, 4)
Sum: [[ 9  4  6  5]
 [ 6  9  5  9]
 [ 8  7 10  7]
 [ 4  7  5  2]]
Elementwise product: [[ 8  4  9  4]
 [ 5 20  6 18]
 [ 7 10 21 10]
 [ 0 10  6  1]]
Power of two: [[ 1  4  9 16]
 [25 16  4  9]
 [49 25  9  4]
 [ 0  4  9  1]]
Elementwise power: [[   1    4   27    4]
 [   5 1024    8  729]
 [   7   25 2187   32]
 [   0   32    9    1]]
Matrix multiplication: [[29 38 38 32]
 [58 49 47 42]
 [72 55 61 54]
 [ 9 21 29 28]]
Minimum: 0
Maximum: 7
Minimum along columns: [0 2 2 1]
Minimum along rows: [1 2 2 0]
Sum: 47
Mean: 2.9375
Diagonal: [1 4 3 1]


In [23]:
a=np.array([0,1,2,3,4])
b=np.array([0.2,0.5,2,0.8])

print (a.dtype) #array of integers
print (b.dtype) #array of floats

int64
float64


In [24]:
mat = np.array(([1,5,2,7],[2,7,3,2],[1,5,2,1]))
print ("mat[0,0]   ->",mat[0,0]) #first row, first column
print ("mat[2][1]  ->",mat[2][1]) #third row, second column (alternate notation)
print ("mat[0]     -> ",mat[0]) #first row of mat
print ("mat[:,0]   -> ",mat[:,0]) #first column of mat. The ":" notation means "leave everything unchanged along this dimension"
print ("mat[0,:]   ->",mat[0,:]) #first row of mat (alternate notation)
print ("mat[0:2,:] ->\n",mat[0:2,:]) #first two rows of mat
print ("mat[:,0:2] ->\n",mat[:,0:2]) #first two columns of mat
print ("mat[-1]    ->",mat[-1]) #last row of mat

mat[0,0]   -> 1
mat[2][1]  -> 5
mat[0]     ->  [1 5 2 7]
mat[:,0]   ->  [1 2 1]
mat[0,:]   -> [1 5 2 7]
mat[0:2,:] ->
 [[1 5 2 7]
 [2 7 3 2]]
mat[:,0:2] ->
 [[1 5]
 [2 7]
 [1 5]]
mat[-1]    -> [1 5 2 1]


In [25]:
mat=np.array([[[1,2],[2,3],[1,2]],
              [[5,2],[-1,4],[0,2]],
              [[0,5],[2,-3],[2,1]]])
print (mat.shape)

(3, 3, 2)


In [26]:
print ("mat[:,:,0] ->", mat[:,:,0]) #3 x 3 matrix contained in the "first channel" of the tensor
print ("mat[:,:,1] ->",mat[:,:,1]) #3 x 3 matrix contained in the "second channel" of the tensor
print ("mat[...,0] ->", mat[...,0]) #3 x 3 matrix contained in the "first channel" of the tensor (alternate notation)
print ("mat[...,1] ->",mat[...,1]) #3 x 3 matrix contained in the "second channel" of the tensor (alternate notation)

mat[:,:,0] -> [[ 1  2  1]
 [ 5 -1  0]
 [ 0  2  2]]
mat[:,:,1] -> [[ 2  3  2]
 [ 2  4  2]
 [ 5 -3  1]]
mat[...,0] -> [[ 1  2  1]
 [ 5 -1  0]
 [ 0  2  2]]
mat[...,1] -> [[ 2  3  2]
 [ 2  4  2]
 [ 5 -3  1]]
